version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "composer"
enabled = true

[[analyzers]]
name = "git"
enabled = true

[analyzers.php.meta]
root = "."

exclude_patterns = [
  "vendor/",
  "node_modules/",
  "storage/",
  "bootstrap/",
  "public/",
  "tests/",
  "*.blade.php",
  "database/",
  "config/"
]

[analyzers.php.config]
security_checks = true
laravel_specific_checks = true
performance_checks = true

[[transformers]]
name = "php-cs-fixer"
enabled = true