version = 1

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "composer"
enabled = true

[[analyzers]]
name = "git"
enabled = true

# تنظیمات خاص آنالایزر PHP
[analyzers.php]
enabled = true

# exclude فایل‌های غیر ضروری
[analyzers.php.meta]
root = "."

exclude = [
  "vendor/",
  "node_modules/",
  "storage/",
  "bootstrap/",
  "public/",
  "tests/",
  "*.blade.php",
  "database/",
  "config/"
]

# تنظیمات transformer
[[transformers]]
name = "php-cs-fixer"
enabled = true

# تنظیمات عمومی
[python]
version = "3.8"

[php]
version = "8.4"

[go]
version = "1.19"

[javascript]
version = "18"

[java]
version = "11"