version = 1
version = 1

test_patterns = [
  "tests/**",
  "test_e2e/**"
]
exclude_patterns = [
  "vendor/**"
]

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["config/bootstrap.php"]

[analyzers.php.meta]
root = "."

exclude_patterns = [
  "vendor/",
  "node_modules/",
  "storage/",
  "bootstrap/",
  "public/",
  "tests/",
  "*.blade.php",
  "database/",
  "config/"
]

[analyzers.php.config]
security_checks = true
laravel_specific_checks = true
performance_checks = true

[[transformers]]
name = "php-cs-fixer"
enabled = true